theme: jekyll-theme-minimal
title: "Hannah Oppenheimer"
description: "Product Designer, Ice Cream Maker"
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
google_analytics: "UA-109421091-1"
