theme: jekyll-theme-minimal
title: "Hannah Hearth"
description: "Product Design Leader"
base_url: https://hannahhearth.com/
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
google_analytics: "UA-109421091-1"
